### PR TITLE
Fix find_available_local_port to work if IPv6 is disabled

### PR DESCRIPTION
**Pull request by pawciobiel**

### CODE REVIEW

**Comment by pawciobiel** [comment]
fix for https://github.com/jaraco/portend/issues/6

**Review by jaraco — COMMENTED** [review]
Hi Pawel. Thanks for the contrib.

I do agree It should work on systems where IPv6 is not available, though I do think those should be few and far between by this point.

If this library is meant to support environments that only support old protocols, I'd like to see a test fixture or CI environment that can support that environment. I don't feel comfortable adding these changes which could subsequently be optimized away again. It's also important to capture the underlying conditions that trigger these failures. I do recall recently dealing with issues in some environments where IPv6 is partially available, though I can't find it now, but it's important to define what it is about the environment that's causing the failure.

I'm tempted to say portend should just rely on systems having IPv6 support. I studied IPv6 in 18 years ago and it's been available for more than a decade in all major platforms. If a platform or implementer is disabling IPv6, there should be a good reason for it.

So ultimately, I don't want to accept changes that make IPv4 the default or preferred protocol or changes that remove the current assertions.  Wherever possible, this library should assume IPv6 or dual-stack environments and only fall back to IPv4 behavior when necessary. It should be able to rely on specified designations like AF_UNSPEC to be agnostic to the available protocols and let the system decide the best family to use.

Given the apparently limited impact of these offending environments, perhaps the best thing would be to build a compatibility shim, something that monkey-patches this module in those delicate or limited environments.

I would be willing to accept more modest changes, such as having `find_available_local_port` accept a family parameter (defaulting to AF_INET6) or having it try AF_INET6 and fallback to AF_INET if necessary, but even that feels like unnecessary complication if in fact all of these other changes are necessary to support these limited environments.

Perhaps let's start with how to replicate these failures in a test environment or with test fixtures that simulate these limited environments?

**Comment by pawciobiel** [comment]
Hi Jason,
Thanks for very detail explanation, I wasn't expecting that. I wouldn't be offended if you prefer not to accept this PR just because you don't like it or it would brake same of your systems. 
I understand that this may make other libs and apps to break.
Also I though I may need to assure you I don't judge on yous or anyone eases believes or opinions.

To reproduce it you can disable IPv6 on your PC/laptop/server/vm. I can try to write a fixture and/or test to do it. 

The way I was thinking about it is:
* In both python2 and python3 the default `family` to `socket.socket` is `AF_INET` this is why I though I could put it there as default too.
* Not all systems support IPv6, I guss many have it turned on by default now (since 2012?) but I don't know which system would have IPv6 set as default.
* I read many systems disable IPv6 deliberately for security reasons.
* I believe many local network/DMZ don't use IPv6
* my virtual machines don't use IPv6

I don't know if you really need to have a good reason to disable IPv6 - I personally don't like cluttered output from `ifconfig`. It's NOT important, but In my opinion it is easier and perhaps less error prone to be explicit and don't rely on system to decide.

Thanks again for all your suggestions, I'll think about this and perhaps send you another one for review.

**Comment by jaraco** [comment]
Thanks for understanding. Let's continue to iterate on this in the the ticket.

**Pull request closed without merging**
